server {
    listen 8081;

    location / {
        proxy_pass http://zitadel:8080;
        proxy_set_header Host localhost:8082;
        proxy_set_header X-Forwarded-Proto http;
        proxy_set_header X-Forwarded-Host localhost:8082;
    }
}
